// Package consts 提供常量定义
package consts

// AddrCode 地区码枚举
type AddrCode string

const (
	// 地区码常量定义，根据地区码表NEW.xlsx生成
	// 常量命名规则：大写字母加下划线格式，使用表格B列值的拼音
	// 常量值：表格A列的值

	// ADDR_CODE_QUAN_GUO 全国
	ADDR_CODE_QUAN_GUO AddrCode = "1"
	// ADDR_CODE_BEI_JING_SHI 北京市
	ADDR_CODE_BEI_JING_SHI AddrCode = "1000"
	// ADDR_CODE_MI_YUN_QU 密云区
	ADDR_CODE_MI_YUN_QU AddrCode = "1027"
	// ADDR_CODE_YAN_QING_QU 延庆区
	ADDR_CODE_YAN_QING_QU AddrCode = "1028"
	// ADDR_CODE_TIAN_JIN_SHI 天津市
	ADDR_CODE_TIAN_JIN_SHI AddrCode = "1100"
	// ADDR_CODE_NING_HE_QU 宁河区
	ADDR_CODE_NING_HE_QU AddrCode = "1121"
	// ADDR_CODE_JING_HAI_QU 静海区
	ADDR_CODE_JING_HAI_QU AddrCode = "1123"
	// ADDR_CODE_TIAN_JIN_SHI_JI_ZHOU_QU 蓟州区
	ADDR_CODE_TIAN_JIN_SHI_JI_ZHOU_QU AddrCode = "1125"
	// ADDR_CODE_BIN_HAI_XIN_QU 滨海新区
	ADDR_CODE_BIN_HAI_XIN_QU AddrCode = "1127"
	// ADDR_CODE_HE_BEI_SHENG 河北省
	ADDR_CODE_HE_BEI_SHENG AddrCode = "1200"
	// ADDR_CODE_SHI_JIA_ZHUANG_SHI 石家庄市
	ADDR_CODE_SHI_JIA_ZHUANG_SHI AddrCode = "1210"
	// ADDR_CODE_JING_XING_XIAN 井陉县
	ADDR_CODE_JING_XING_XIAN AddrCode = "1211"
	// ADDR_CODE_LU_QUAN_QU 鹿泉区
	ADDR_CODE_LU_QUAN_QU AddrCode = "1212"
	// ADDR_CODE_ZHENG_DING_XIAN 正定县
	ADDR_CODE_ZHENG_DING_XIAN AddrCode = "1213"
	// ADDR_CODE_LUAN_CHENG_QU 栾城区
	ADDR_CODE_LUAN_CHENG_QU AddrCode = "1214"
	// ADDR_CODE_CHANG_AN_QU 长安区
	ADDR_CODE_CHANG_AN_QU AddrCode = "1215"
	// ADDR_CODE_JIA_ZHUANG_SHI_QIAO_XI_QU 桥西区
	ADDR_CODE_JIA_ZHUANG_SHI_QIAO_XI_QU AddrCode = "1216"
	// ADDR_CODE_SHI_JIA_ZHUANG_SHI_XIN_HUA_QU 新华区
	ADDR_CODE_SHI_JIA_ZHUANG_SHI_XIN_HUA_QU AddrCode = "1217"
	// ADDR_CODE_JING_XING_KUANG_QU 井陉矿区
	ADDR_CODE_JING_XING_KUANG_QU AddrCode = "1218"
	// ADDR_CODE_YU_HUA_QU 裕华区
	ADDR_CODE_YU_HUA_QU AddrCode = "1219"
	// ADDR_CODE_XIN_JI_SHI 辛集市
	ADDR_CODE_XIN_JI_SHI AddrCode = "1221"
	// ADDR_CODE_JIN_ZHOU_SHI 晋州市
	ADDR_CODE_JIN_ZHOU_SHI AddrCode = "1222"
	// ADDR_CODE_SHEN_ZE_XIAN 深泽县
	ADDR_CODE_SHEN_ZE_XIAN AddrCode = "1223"
	// ADDR_CODE_WU_JI_XIAN 无极县
	ADDR_CODE_WU_JI_XIAN AddrCode = "1224"
	// ADDR_CODE_GAO_CHENG_QU 藁城区
	ADDR_CODE_GAO_CHENG_QU AddrCode = "1225"
	// ADDR_CODE_ZHAO_XIAN 赵县
	ADDR_CODE_ZHAO_XIAN AddrCode = "1226"
	// ADDR_CODE_XIN_LE_SHI 新乐市
	ADDR_CODE_XIN_LE_SHI AddrCode = "1227"
	// ADDR_CODE_GAO_YI_XIAN 高邑县
	ADDR_CODE_GAO_YI_XIAN AddrCode = "1228"
	// ADDR_CODE_YUAN_SHI_XIAN 元氏县
	ADDR_CODE_YUAN_SHI_XIAN AddrCode = "1229"
	// ADDR_CODE_ZAN_HUANG_XIAN 赞皇县
	ADDR_CODE_ZAN_HUANG_XIAN AddrCode = "1231"
	// ADDR_CODE_PING_SHAN_XIAN 平山县
	ADDR_CODE_PING_SHAN_XIAN AddrCode = "1232"
	// ADDR_CODE_LING_SHOU_XIAN 灵寿县
	ADDR_CODE_LING_SHOU_XIAN AddrCode = "1233"
	// ADDR_CODE_XING_TANG_XIAN 行唐县
	ADDR_CODE_XING_TANG_XIAN AddrCode = "1234"
	// ADDR_CODE_TANG_SHAN_SHI 唐山市
	ADDR_CODE_TANG_SHAN_SHI AddrCode = "1240"
	// ADDR_CODE_LU_NAN_QU 路南区
	ADDR_CODE_LU_NAN_QU AddrCode = "1241"
	// ADDR_CODE_LU_BEI_QU 路北区
	ADDR_CODE_LU_BEI_QU AddrCode = "1242"
	// ADDR_CODE_LUAN_ZHOU_SHI 滦州市
	ADDR_CODE_LUAN_ZHOU_SHI AddrCode = "1243"
	// ADDR_CODE_LUAN_NAN_XIAN 滦南县
	ADDR_CODE_LUAN_NAN_XIAN AddrCode = "1244"
	// ADDR_CODE_LE_TING_XIAN 乐亭县
	ADDR_CODE_LE_TING_XIAN AddrCode = "1245"
	// ADDR_CODE_QIAN_AN_SHI 迁安市
	ADDR_CODE_QIAN_AN_SHI AddrCode = "1246"
	// ADDR_CODE_QIAN_XI_XIAN 迁西县
	ADDR_CODE_QIAN_XI_XIAN AddrCode = "1247"
	// ADDR_CODE_ZUN_HUA_SHI 遵化市
	ADDR_CODE_ZUN_HUA_SHI AddrCode = "1248"
	// ADDR_CODE_YU_TIAN_XIAN 玉田县
	ADDR_CODE_YU_TIAN_XIAN AddrCode = "1249"
	// ADDR_CODE_FENG_NAN_QU 丰南区
	ADDR_CODE_FENG_NAN_QU AddrCode = "1251"
	// ADDR_CODE_GU_YE_QU 古冶区
	ADDR_CODE_GU_YE_QU AddrCode = "1252"
	// ADDR_CODE_KAI_PING_QU 开平区
	ADDR_CODE_KAI_PING_QU AddrCode = "1253"
	// ADDR_CODE_FENG_RUN_QU 丰润区
	ADDR_CODE_FENG_RUN_QU AddrCode = "1254"
	// ADDR_CODE_CAO_FEI_DIAN_QU 曹妃甸区
	ADDR_CODE_CAO_FEI_DIAN_QU AddrCode = "1255"
	// ADDR_CODE_QIN_HUANG_DAO_SHI 秦皇岛市
	ADDR_CODE_QIN_HUANG_DAO_SHI AddrCode = "1260"
	// ADDR_CODE_QING_LONG_MAN_ZU_ZI_ZHI_XIAN 青龙满族自治县
	ADDR_CODE_QING_LONG_MAN_ZU_ZI_ZHI_XIAN AddrCode = "1261"
	// ADDR_CODE_CHANG_LI_XIAN 昌黎县
	ADDR_CODE_CHANG_LI_XIAN AddrCode = "1262"
	// ADDR_CODE_FU_NING_QU 抚宁区
	ADDR_CODE_FU_NING_QU AddrCode = "1263"
	// ADDR_CODE_LU_LONG_XIAN 卢龙县
	ADDR_CODE_LU_LONG_XIAN AddrCode = "1264"
	// ADDR_CODE_HAI_GANG_QU 海港区
	ADDR_CODE_HAI_GANG_QU AddrCode = "1265"
	// ADDR_CODE_SHAN_HAI_GU_QU 山海关区
	ADDR_CODE_SHAN_HAI_GU_QU AddrCode = "1266"
	// ADDR_CODE_BEI_DAI_HE_QU 北戴河区
	ADDR_CODE_BEI_DAI_HE_QU AddrCode = "1267"
	// ADDR_CODE_HAN_DAN_SHI 邯郸市
	ADDR_CODE_HAN_DAN_SHI AddrCode = "1270"
	// ADDR_CODE_HAN_DAN_XIAN 邯郸县
	ADDR_CODE_HAN_DAN_XIAN AddrCode = "1271"
	// ADDR_CODE_HAN_SHAN_QU 邯山区
	ADDR_CODE_HAN_SHAN_QU AddrCode = "1272"
	// ADDR_CODE_CONG_TAI_QU 丛台区
	ADDR_CODE_CONG_TAI_QU AddrCode = "1273"
	// ADDR_CODE_FU_XING_QU 复兴区
	ADDR_CODE_FU_XING_QU AddrCode = "1274"
	// ADDR_CODE_FENG_FENG_KUANG_QU 峰峰矿区
	ADDR_CODE_FENG_FENG_KUANG_QU AddrCode = "1275"
	// ADDR_CODE_DA_MING_XIAN 大名县
	ADDR_CODE_DA_MING_XIAN AddrCode = "1281"
	// ADDR_CODE_HAN_DAN_SHI_WEI_XIAN 魏县
	ADDR_CODE_HAN_DAN_SHI_WEI_XIAN AddrCode = "1282"
	// ADDR_CODE_QU_ZHOU_XIAN 曲周县
	ADDR_CODE_QU_ZHOU_XIAN AddrCode = "1283"
	// ADDR_CODE_QIU_XIAN 邱县
	ADDR_CODE_QIU_XIAN AddrCode = "1284"
	// ADDR_CODE_JI_ZE_XIAN 鸡泽县
	ADDR_CODE_JI_ZE_XIAN AddrCode = "1285"
	// ADDR_CODE_FEI_XIANG_QU 肥乡区
	ADDR_CODE_FEI_XIANG_QU AddrCode = "1286"
	// ADDR_CODE_GUANG_PING_XIAN 广平县
	ADDR_CODE_GUANG_PING_XIAN AddrCode = "1287"
	// ADDR_CODE_CHENG_AN_XIAN 成安县
	ADDR_CODE_CHENG_AN_XIAN AddrCode = "1288"
	// ADDR_CODE_LIN_ZHANG_XIAN 临漳县
	ADDR_CODE_LIN_ZHANG_XIAN AddrCode = "1289"
	// ADDR_CODE_CI_XIAN 磁县
	ADDR_CODE_CI_XIAN AddrCode = "1291"
	// ADDR_CODE_SHE_XIAN 涉县
	ADDR_CODE_SHE_XIAN AddrCode = "1292"
	// ADDR_CODE_YONG_NIAN_QU 永年区
	ADDR_CODE_YONG_NIAN_QU AddrCode = "1293"
	// ADDR_CODE_GUAN_TAO_XIAN 馆陶县
	ADDR_CODE_GUAN_TAO_XIAN AddrCode = "1294"
	// ADDR_CODE_WU_AN_SHI 武安市
	ADDR_CODE_WU_AN_SHI AddrCode = "1295"
	// ADDR_CODE_XING_TAI_SHI 邢台市
	ADDR_CODE_XING_TAI_SHI AddrCode = "1310"
	// ADDR_CODE_XING_TAI_XIAN 邢台县
	ADDR_CODE_XING_TAI_XIAN AddrCode = "1311"
	// ADDR_CODE_XIANG_DOU_QU 襄都区
	ADDR_CODE_XIANG_DOU_QU AddrCode = "1312"
	// ADDR_CODE_XIN_DU_QU 信都区
	ADDR_CODE_XIN_DU_QU AddrCode = "1313"
	// ADDR_CODE_NAN_GONG_SHI 南宫市
	ADDR_CODE_NAN_GONG_SHI AddrCode = "1321"
	// ADDR_CODE_SHA_HE_SHI 沙河市
	ADDR_CODE_SHA_HE_SHI AddrCode = "1322"
	// ADDR_CODE_LIN_CHENG_XIAN 临城县
	ADDR_CODE_LIN_CHENG_XIAN AddrCode = "1323"
	// ADDR_CODE_NEI_QIU_XIAN 内丘县
	ADDR_CODE_NEI_QIU_XIAN AddrCode = "1324"
	// ADDR_CODE_BAI_XIANG_XIAN 柏乡县
	ADDR_CODE_BAI_XIANG_XIAN AddrCode = "1325"
	// ADDR_CODE_LONG_YAO_XIAN 隆尧县
	ADDR_CODE_LONG_YAO_XIAN AddrCode = "1326"
	// ADDR_CODE_REN_ZE_QU 任泽区
	ADDR_CODE_REN_ZE_QU AddrCode = "1327"
	// ADDR_CODE_NAN_HE_QU 南和区
	ADDR_CODE_NAN_HE_QU AddrCode = "1328"
	// ADDR_CODE_NING_JIN_XIAN 宁晋县
	ADDR_CODE_NING_JIN_XIAN AddrCode = "1329"
	// ADDR_CODE_JU_LU_XIAN 巨鹿县
	ADDR_CODE_JU_LU_XIAN AddrCode = "1331"
	// ADDR_CODE_XIN_HE_XIAN 新河县
	ADDR_CODE_XIN_HE_XIAN AddrCode = "1332"
	// ADDR_CODE_GUANG_ZONG_XIAN 广宗县
	ADDR_CODE_GUANG_ZONG_XIAN AddrCode = "1333"
	// ADDR_CODE_PING_XIANG_XIAN 平乡县
	ADDR_CODE_PING_XIANG_XIAN AddrCode = "1334"
	// ADDR_CODE_WEI_XIAN 威县
	ADDR_CODE_XING_TAI_SHI_WEI_XIAN AddrCode = "1335"
	// ADDR_CODE_QING_HE_XIAN 清河县
	ADDR_CODE_QING_HE_XIAN AddrCode = "1336"
	// ADDR_CODE_SHA_HE_SHI_LIN_XI_XIAN 临西县
	ADDR_CODE_SHA_HE_SHI_LIN_XI_XIAN AddrCode = "1337"
	// ADDR_CODE_BAO_DING_SHI 保定市
	ADDR_CODE_BAO_DING_SHI AddrCode = "1340"
	// ADDR_CODE_MAN_CHENG_QU 满城区
	ADDR_CODE_MAN_CHENG_QU AddrCode = "1341"
	// ADDR_CODE_QING_YUAN_QU 清苑区
	ADDR_CODE_QING_YUAN_QU AddrCode = "1342"
	// ADDR_CODE_JING_XIU_QU 竞秀区
	ADDR_CODE_JING_XIU_QU AddrCode = "1343"
	// ADDR_CODE_LIAN_CHI_QU 莲池区
	ADDR_CODE_LIAN_CHI_QU AddrCode = "1344"
	// ADDR_CODE_DING_ZHOU_SHI 定州市
	ADDR_CODE_DING_ZHOU_SHI AddrCode = "1351"
	// ADDR_CODE_ZHUO_ZHOU_SHI 涿州市
	ADDR_CODE_ZHUO_ZHOU_SHI AddrCode = "1352"
	// ADDR_CODE_YI_XIAN 易县
	ADDR_CODE_YI_XIAN AddrCode = "1353"
	// ADDR_CODE_XU_SHUI_QU 徐水区
	ADDR_CODE_XU_SHUI_QU AddrCode = "1354"
	// ADDR_CODE_LAI_YUAN_XIAN 涞源县
	ADDR_CODE_LAI_YUAN_XIAN AddrCode = "1355"
	// ADDR_CODE_DING_XING_XIAN 定兴县
	ADDR_CODE_DING_XING_XIAN AddrCode = "1356"
	// ADDR_CODE_SHUN_PING_XIAN 顺平县
	ADDR_CODE_SHUN_PING_XIAN AddrCode = "1357"
	// ADDR_CODE_TANG_XIAN 唐县
	ADDR_CODE_TANG_XIAN AddrCode = "1358"
	// ADDR_CODE_WANG_DU_XIAN 望都县
	ADDR_CODE_WANG_DU_XIAN AddrCode = "1359"
	// ADDR_CODE_LAI_SHUI_XIAN 涞水县
	ADDR_CODE_LAI_SHUI_XIAN AddrCode = "1361"
	// ADDR_CODE_GAO_YANG_XIAN 高阳县
	ADDR_CODE_GAO_YANG_XIAN AddrCode = "1362"
	// ADDR_CODE_AN_XIN_XIAN 安新县
	ADDR_CODE_AN_XIN_XIAN AddrCode = "1363"
	// ADDR_CODE_XIONG_XIAN 雄县
	ADDR_CODE_XIONG_XIAN AddrCode = "1364"
	// ADDR_CODE_RONG_CHENG_XIAN 容城县
	ADDR_CODE_RONG_CHENG_XIAN AddrCode = "1365"
	// ADDR_CODE_GAO_BEI_DIAN_SHI 高碑店市
	ADDR_CODE_GAO_BEI_DIAN_SHI AddrCode = "1366"
	// ADDR_CODE_QU_YANG_XIAN 曲阳县
	ADDR_CODE_QU_YANG_XIAN AddrCode = "1367"
	// ADDR_CODE_FU_PING_XIAN 阜平县
	ADDR_CODE_FU_PING_XIAN AddrCode = "1368"
	// ADDR_CODE_AN_GUO_SHI 安国市
	ADDR_CODE_AN_GUO_SHI AddrCode = "1369"
	// ADDR_CODE_BO_YE_XIAN 博野县
	ADDR_CODE_BO_YE_XIAN AddrCode = "1371"
	// ADDR_CODE_LI_XIAN 蠡县
	ADDR_CODE_LI_XIAN AddrCode = "1372"
	// ADDR_CODE_ZHANG_JIA_KOU_SHI 张家口市
	ADDR_CODE_ZHANG_JIA_KOU_SHI AddrCode = "1380"
	// ADDR_CODE_XUAN_HUA_XIAN 宣化县
	ADDR_CODE_XUAN_HUA_XIAN AddrCode = "1381"
	// ADDR_CODE_QIAO_DONG_QU 桥东区
	ADDR_CODE_QIAO_DONG_QU AddrCode = "1382"
	// ADDR_CODE_JIA_KOU_SHI_QIAO_XI_QU 桥西区
	ADDR_CODE_JIA_KOU_SHI_QIAO_XI_QU AddrCode = "1383"
	// ADDR_CODE_XUAN_HUA_QU 宣化区
	ADDR_CODE_XUAN_HUA_QU AddrCode = "1384"
	// ADDR_CODE_XIA_HUA_YUAN_QU 下花园区
	ADDR_CODE_XIA_HUA_YUAN_QU AddrCode = "1385"
	// ADDR_CODE_ZHANG_BEI_XIAN 张北县
	ADDR_CODE_ZHANG_BEI_XIAN AddrCode = "1391"
	// ADDR_CODE_KANG_BAO_XIAN 康保县
	ADDR_CODE_KANG_BAO_XIAN AddrCode = "1392"
	// ADDR_CODE_GU_YUAN_XIAN 沽源县
	ADDR_CODE_GU_YUAN_XIAN AddrCode = "1393"
	// ADDR_CODE_SHANG_YI_XIAN 尚义县
	ADDR_CODE_SHANG_YI_XIAN AddrCode = "1394"
	// ADDR_CODE_ZHANG_JIA_KOU_SHI_YU_XIAN 蔚县
	ADDR_CODE_ZHANG_JIA_KOU_SHI_YU_XIAN AddrCode = "1395"
	// ADDR_CODE_YANG_YUAN_XIAN 阳原县
	ADDR_CODE_YANG_YUAN_XIAN AddrCode = "1396"
	// ADDR_CODE_HUAI_AN_XIAN 怀安县
	ADDR_CODE_HUAI_AN_XIAN AddrCode = "1397"
	// ADDR_CODE_WAN_QUAN_QU 万全区
	ADDR_CODE_WAN_QUAN_QU AddrCode = "1398"
	// ADDR_CODE_HUAI_LAI_XIAN 怀来县
	ADDR_CODE_HUAI_LAI_XIAN AddrCode = "1399"
	// ADDR_CODE_ZHUO_LU_XIAN 涿鹿县
	ADDR_CODE_ZHUO_LU_XIAN AddrCode = "1401"
	// ADDR_CODE_CHI_CHENG_XIAN 赤城县
	ADDR_CODE_CHI_CHENG_XIAN AddrCode = "1402"
	// ADDR_CODE_CHONG_LI_QU 崇礼区
	ADDR_CODE_CHONG_LI_QU AddrCode = "1403"
	// ADDR_CODE_CHENG_DE_SHI 承德市
	ADDR_CODE_CHENG_DE_SHI AddrCode = "1410"
	// ADDR_CODE_CHENG_DE_XIAN 承德县
	ADDR_CODE_CHENG_DE_XIAN AddrCode = "1411"
	// ADDR_CODE_SHUANG_LUAN_QU 双滦区
	ADDR_CODE_SHUANG_LUAN_QU AddrCode = "1413"
	// ADDR_CODE_YING_SHOU_YING_ZI_KUANG_QU 鹰手营子矿区
	ADDR_CODE_YING_SHOU_YING_ZI_KUANG_QU AddrCode = "1414"
	// ADDR_CODE_KUAN_CHENG_MAN_ZU_ZI_ZHI_XIAN 宽城满族自治县
	ADDR_CODE_KUAN_CHENG_MAN_ZU_ZI_ZHI_XIAN AddrCode = "1421"
	// ADDR_CODE_XING_LONG_XIAN 兴隆县
	ADDR_CODE_XING_LONG_XIAN AddrCode = "1422"
	// ADDR_CODE_PING_QUAN_SHI 平泉市
	ADDR_CODE_PING_QUAN_SHI AddrCode = "1423"
	// ADDR_CODE_LUAN_PING_XIAN 滦平县
	ADDR_CODE_LUAN_PING_XIAN AddrCode = "1424"
	// ADDR_CODE_FENG_NING_MAN_ZU_ZI_ZHI_XIAN 丰宁满族自治县
	ADDR_CODE_FENG_NING_MAN_ZU_ZI_ZHI_XIAN AddrCode = "1425"
	// ADDR_CODE_LONG_HUA_XIAN 隆化县
	ADDR_CODE_LONG_HUA_XIAN AddrCode = "1426"
	// ADDR_CODE_WEI_CHANG_MAN_ZU_MENG_GU_ZU_ZI_ZHI_XIAN 围场满族蒙古族自治县
	ADDR_CODE_WEI_CHANG_MAN_ZU_MENG_GU_ZU_ZI_ZHI_XIAN AddrCode = "1427"
	// ADDR_CODE_CANG_ZHOU_SHI 沧州市
	ADDR_CODE_CANG_ZHOU_SHI AddrCode = "1430"
	// ADDR_CODE_CANG_XIAN 沧县
	ADDR_CODE_CANG_XIAN AddrCode = "1431"
	// ADDR_CODE_QING_XIAN 青县
	ADDR_CODE_QING_XIAN AddrCode = "1432"
	// ADDR_CODE_XIN_HUA_QU_TWO 新华区
	ADDR_CODE_XIN_HUA_QU_TWO AddrCode = "1433"
	// ADDR_CODE_PO_TOU_SHI 泊头市
	ADDR_CODE_PO_TOU_SHI AddrCode = "1441"
	// ADDR_CODE_REN_QIU_SHI 任丘市
	ADDR_CODE_REN_QIU_SHI AddrCode = "1442"
	// ADDR_CODE_HE_JIAN_SHI 河间市
	ADDR_CODE_HE_JIAN_SHI AddrCode = "1443"
	// ADDR_CODE_SU_NING_XIAN 肃宁县
	ADDR_CODE_SU_NING_XIAN AddrCode = "1444"
	// ADDR_CODE_XIAN_XIAN 献县
	ADDR_CODE_XIAN_XIAN AddrCode = "1445"
	// ADDR_CODE_WU_QIAO_XIAN 吴桥县
	ADDR_CODE_WU_QIAO_XIAN AddrCode = "1446"
	// ADDR_CODE_DONG_GUANG_XIAN 东光县
	ADDR_CODE_DONG_GUANG_XIAN AddrCode = "1447"
	// ADDR_CODE_NAN_PI_XIAN 南皮县
	ADDR_CODE_NAN_PI_XIAN AddrCode = "1448"
	// ADDR_CODE_YAN_SHAN_XIAN 盐山县
	ADDR_CODE_YAN_SHAN_XIAN AddrCode = "1449"
	// ADDR_CODE_HUANG_HUA_SHI 黄骅市
	ADDR_CODE_HUANG_HUA_SHI AddrCode = "1451"
	// ADDR_CODE_MENG_CUN_HUI_ZU_ZI_ZHI_XIAN 孟村回族自治县
	ADDR_CODE_MENG_CUN_HUI_ZU_ZI_ZHI_XIAN AddrCode = "1452"
	// ADDR_CODE_HAI_XING_XIAN 海兴县
	ADDR_CODE_HAI_XING_XIAN AddrCode = "1453"
	// ADDR_CODE_YUN_HE_QU 运河区
	ADDR_CODE_YUN_HE_QU AddrCode = "1454"
	// ADDR_CODE_LANG_FANG_SHI 廊坊市
	ADDR_CODE_LANG_FANG_SHI AddrCode = "1460"
	// ADDR_CODE_SAN_HE_SHI 三河市
	ADDR_CODE_SAN_HE_SHI AddrCode = "1461"
	// ADDR_CODE_GU_AN_XIAN 固安县
	ADDR_CODE_GU_AN_XIAN AddrCode = "1462"
	// ADDR_CODE_YONG_QING_XIAN 永清县
	ADDR_CODE_YONG_QING_XIAN AddrCode = "1463"
	// ADDR_CODE_XIANG_HE_XIAN 香河县
	ADDR_CODE_XIANG_HE_XIAN AddrCode = "1464"
	// ADDR_CODE_DA_CHENG_XIAN 大城县
	ADDR_CODE_DA_CHENG_XIAN AddrCode = "1465"
	// ADDR_CODE_WEN_AN_XIAN 文安县
	ADDR_CODE_WEN_AN_XIAN AddrCode = "1466"
	// ADDR_CODE_BA_ZHOU_SHI 霸州市
	ADDR_CODE_BA_ZHOU_SHI AddrCode = "1467"
	// ADDR_CODE_DA_CHANG_HUI_ZU_ZI_ZHI_XIAN 大厂回族自治县
	ADDR_CODE_DA_CHANG_HUI_ZU_ZI_ZHI_XIAN AddrCode = "1468"
	// ADDR_CODE_AN_CI_QU 安次区
	ADDR_CODE_AN_CI_QU AddrCode = "1469"
	// ADDR_CODE_GUANG_YANG_QU 广阳区
	ADDR_CODE_GUANG_YANG_QU AddrCode = "1471"
	// ADDR_CODE_HENG_SHUI_SHI 衡水市
	ADDR_CODE_HENG_SHUI_SHI AddrCode = "1480"
	// ADDR_CODE_JI_ZHOU_QU_TWO 冀州区
	ADDR_CODE_JI_ZHOU_QU_TOW AddrCode = "1482"
	// ADDR_CODE_ZAO_QIANG_XIAN 枣强县
	ADDR_CODE_ZAO_QIANG_XIAN AddrCode = "1483"
	// ADDR_CODE_WU_YI_XIAN 武邑县
	ADDR_CODE_WU_YI_XIAN AddrCode = "1484"
	// ADDR_CODE_SHEN_ZHOU_SHI 深州市
	ADDR_CODE_SHEN_ZHOU_SHI AddrCode = "1485"
	// ADDR_CODE_WU_QIANG_XIAN 武强县
	ADDR_CODE_WU_QIANG_XIAN AddrCode = "1486"
	// ADDR_CODE_RAO_YANG_XIAN 饶阳县
	ADDR_CODE_RAO_YANG_XIAN AddrCode = "1487"
	// ADDR_CODE_AN_PING_XIAN 安平县
	ADDR_CODE_AN_PING_XIAN AddrCode = "1488"
	// ADDR_CODE_GU_CHENG_XIAN 故城县
	ADDR_CODE_GU_CHENG_XIAN AddrCode = "1489"
	// ADDR_CODE_JING_XIAN 景县
	ADDR_CODE_JING_XIAN AddrCode = "1491"
	// ADDR_CODE_FU_CHENG_XIAN 阜城县
	ADDR_CODE_FU_CHENG_XIAN AddrCode = "1492"
	// ADDR_CODE_SHAN_XI_SHENG 山西省
	ADDR_CODE_SHAN_XI_SHENG AddrCode = "1600"
	// ADDR_CODE_TAI_YUAN_SHI 太原市
	ADDR_CODE_TAI_YUAN_SHI AddrCode = "1610"
	// ADDR_CODE_QING_XU_XIAN 清徐县
	ADDR_CODE_QING_XU_XIAN AddrCode = "1611"
	// ADDR_CODE_YANG_QU_XIAN 阳曲县
	ADDR_CODE_YANG_QU_XIAN AddrCode = "1612"
	// ADDR_CODE_LOU_FAN_XIAN 娄烦县
	ADDR_CODE_LOU_FAN_XIAN AddrCode = "1613"
	// ADDR_CODE_GU_JIAO_SHI 古交市
	ADDR_CODE_GU_JIAO_SHI AddrCode = "1614"
	// ADDR_CODE_JIAN_CAO_PING_QU 尖草坪区
	ADDR_CODE_JIAN_CAO_PING_QU AddrCode = "1615"
	// ADDR_CODE_XIAO_DIAN_QU 小店区
	ADDR_CODE_XIAO_DIAN_QU AddrCode = "1616"
	// ADDR_CODE_YING_ZE_QU 迎泽区
	ADDR_CODE_YING_ZE_QU AddrCode = "1617"
	// ADDR_CODE_XING_HUA_LING_QU 杏花岭区
	ADDR_CODE_XING_HUA_LING_QU AddrCode = "1618"
	// ADDR_CODE_WAN_BAI_LIN_QU 万柏林区
	ADDR_CODE_WAN_BAI_LIN_QU AddrCode = "1619"
	// ADDR_CODE_DA_TONG_SHI 大同市
	ADDR_CODE_DA_TONG_SHI AddrCode = "1620"
	// ADDR_CODE_JIN_YUAN_QU 晋源区
	ADDR_CODE_JIN_YUAN_QU AddrCode = "1621"
	// ADDR_CODE_YANG_GAO_XIAN 阳高县
	ADDR_CODE_YANG_GAO_XIAN AddrCode = "1631"
	// ADDR_CODE_TIAN_ZHEN_XIAN 天镇县
	ADDR_CODE_TIAN_ZHEN_XIAN AddrCode = "1632"
	// ADDR_CODE_GUANG_LING_XIAN 广灵县
	ADDR_CODE_GUANG_LING_XIAN AddrCode = "1633"
	// ADDR_CODE_LING_QIU_XIAN 灵丘县
	ADDR_CODE_LING_QIU_XIAN AddrCode = "1634"
	// ADDR_CODE_HUN_YUAN_XIAN 浑源县
	ADDR_CODE_HUN_YUAN_XIAN AddrCode = "1635"
	// ADDR_CODE_ZUO_YUN_XIAN 左云县
	ADDR_CODE_ZUO_YUN_XIAN AddrCode = "1637"
	// ADDR_CODE_NAN_JIAO_QU 南郊区
	ADDR_CODE_NAN_JIAO_QU AddrCode = "1638"
	// ADDR_CODE_YUN_ZHOU_QU 云州区
	ADDR_CODE_YUN_ZHOU_QU AddrCode = "1639"
	// ADDR_CODE_PING_CHENG_QU 平城区
	ADDR_CODE_PING_CHENG_QU AddrCode = "1641"
	// ADDR_CODE_YUN_GANG_QU 云冈区
	ADDR_CODE_YUN_GANG_QU AddrCode = "1642"
	// ADDR_CODE_XIN_RONG_QU 新荣区
	ADDR_CODE_XIN_RONG_QU AddrCode = "1643"
	// ADDR_CODE_YANG_QUAN_SHI 阳泉市
	ADDR_CODE_YANG_QUAN_SHI AddrCode = "1650"
	// ADDR_CODE_PING_DING_XIAN 平定县
	ADDR_CODE_PING_DING_XIAN AddrCode = "1651"
	// ADDR_CODE_YU_XIAN_TWO 盂县
	ADDR_CODE_YU_XIAN_TWO AddrCode = "1652"
	// ADDR_CODE_CHENG_QU 城区
	ADDR_CODE_YU_XIAN_TWO_CHENG_QU AddrCode = "1653"
	// ADDR_CODE_YU_XIAN_TWO_KUANG_QU 矿区
	ADDR_CODE_YU_XIAN_TWO_KUANG_QU AddrCode = "1654"
	// ADDR_CODE_JIAO_QU 郊区
	ADDR_CODE_YU_XIAN_TWO_JIAO_QU AddrCode = "1655"
	// ADDR_CODE_CHANG_ZHI_SHI 长治市
	ADDR_CODE_CHANG_ZHI_SHI AddrCode = "1660"
	// ADDR_CODE_SHANG_DANG_QU 上党区
	ADDR_CODE_SHANG_DANG_QU AddrCode = "1661"
	// ADDR_CODE_LU_CHENG_QU 潞城区
	ADDR_CODE_LU_CHENG_QU AddrCode = "1662"
	// ADDR_CODE_XIANG_YUAN_XIAN 襄垣县
	ADDR_CODE_XIANG_YUAN_XIAN AddrCode = "1663"
	// ADDR_CODE_TUN_LIU_QU 屯留区
	ADDR_CODE_TUN_LIU_QU AddrCode = "1664"
	// ADDR_CODE_PIN_SHUN_XIAN 平顺县
	ADDR_CODE_PIN_SHUN_XIAN AddrCode = "1665"
	// ADDR_CODE_LI_CHENG_XIAN 黎城县
	ADDR_CODE_LI_CHENG_XIAN AddrCode = "1666"
	// ADDR_CODE_HU_GUAN_XIAN 壶关县
	ADDR_CODE_HU_GUAN_XIAN AddrCode = "1667"
	// ADDR_CODE_ZHANG_ZI_XIAN 长子县
	ADDR_CODE_ZHANG_ZI_XIAN AddrCode = "1668"
	// ADDR_CODE_WU_XIANG_XIAN 武乡县
	ADDR_CODE_WU_XIANG_XIAN AddrCode = "1669"
	// ADDR_CODE_QIN_XIAN 沁县
	ADDR_CODE_QIN_XIAN AddrCode = "1671"
	// ADDR_CODE_QIN_YUAN_XIAN 沁源县
	ADDR_CODE_QIN_YUAN_XIAN AddrCode = "1672"
	// ADDR_CODE_LU_ZHOU_QU 潞州区
	ADDR_CODE_LU_ZHOU_QU AddrCode = "1673"
	// ADDR_CODE_JIAO_QU 郊区
	ADDR_CODE_JIAO_QU AddrCode = "1674"
	// ADDR_CODE_JIN_CHENG_SHI 晋城市
	ADDR_CODE_JIN_CHENG_SHI AddrCode = "1680"
	// ADDR_CODE_QIN_SHUI_XIAN 沁水县
	ADDR_CODE_QIN_SHUI_XIAN AddrCode = "1681"
	// ADDR_CODE_YANG_CHENG_XIAN 阳城县
	ADDR_CODE_YANG_CHENG_XIAN AddrCode = "1682"
	// ADDR_CODE_GAO_PING_SHI 高平市
	ADDR_CODE_GAO_PING_SHI AddrCode = "1683"
	// ADDR_CODE_LING_CHUAN_XIAN 陵川县
	ADDR_CODE_LING_CHUAN_XIAN AddrCode = "1684"
	// ADDR_CODE_ZE_ZHOU_XIAN 泽州县
	ADDR_CODE_ZE_ZHOU_XIAN AddrCode = "1685"
	// ADDR_CODE_CHENG_QU 城区
	ADDR_CODE_CHENG_QU AddrCode = "1686"
	// ADDR_CODE_SHUO_ZHOU_SHI 朔州市
	ADDR_CODE_SHUO_ZHOU_SHI AddrCode = "1690"
	// ADDR_CODE_SHAN_YIN_XIAN 山阴县
	ADDR_CODE_SHAN_YIN_XIAN AddrCode = "1691"
	// ADDR_CODE_YING_XIAN 应县
	ADDR_CODE_YING_XIAN AddrCode = "1692"
	// ADDR_CODE_YOU_YU_XIAN 右玉县
	ADDR_CODE_YOU_YU_XIAN AddrCode = "1693"
	// ADDR_CODE_HUAI_REN_SHI 怀仁市
	ADDR_CODE_HUAI_REN_SHI AddrCode = "1694"
	// ADDR_CODE_SHUO_CHENG_QU 朔城区
	ADDR_CODE_SHUO_CHENG_QU AddrCode = "1695"
	// ADDR_CODE_PING_LU_QU 平鲁区
	ADDR_CODE_PING_LU_QU AddrCode = "1696"
	// ADDR_CODE_XIN_ZHOU_SHI 忻州市
	ADDR_CODE_XIN_ZHOU_SHI AddrCode = "1710"
	// ADDR_CODE_DING_XIANG_XIAN 定襄县
	ADDR_CODE_DING_XIANG_XIAN AddrCode = "1712"
	// ADDR_CODE_WU_TAI_XIAN 五台县
	ADDR_CODE_WU_TAI_XIAN AddrCode = "1713"
	// ADDR_CODE_YUAN_PING_SHI 原平市
	ADDR_CODE_YUAN_PING_SHI AddrCode = "1714"
	// ADDR_CODE_DAI_XIAN 代县
	ADDR_CODE_DAI_XIAN AddrCode = "1715"
	// ADDR_CODE_FAN_SHI_XIAN 繁峙县
	ADDR_CODE_FAN_SHI_XIAN AddrCode = "1716"
	// ADDR_CODE_NING_WU_XIAN 宁武县
	ADDR_CODE_NING_WU_XIAN AddrCode = "1717"
	// ADDR_CODE_JING_LE_XIAN 静乐县
	ADDR_CODE_JING_LE_XIAN AddrCode = "1718"
	// ADDR_CODE_SHEN_CHI_XIAN 神池县
	ADDR_CODE_SHEN_CHI_XIAN AddrCode = "1719"
	// ADDR_CODE_WU_ZHAI_XIAN 五寨县
	ADDR_CODE_WU_ZHAI_XIAN AddrCode = "1721"
	// ADDR_CODE_KE_LAN_XIAN 岢岚县
	ADDR_CODE_KE_LAN_XIAN AddrCode = "1722"
	// ADDR_CODE_HE_QU_XIAN 河曲县
	ADDR_CODE_HE_QU_XIAN AddrCode = "1723"
	// ADDR_CODE_BAO_DE_XIAN 保德县
	ADDR_CODE_BAO_DE_XIAN AddrCode = "1724"
	// ADDR_CODE_PIAN_GUAN_XIAN 偏关县
	ADDR_CODE_PIAN_GUAN_XIAN AddrCode = "1725"
	// ADDR_CODE_XIN_FU_QU 忻府区
	ADDR_CODE_XIN_FU_QU AddrCode = "1726"
	// ADDR_CODE_LV_LIANG_SHI 吕梁市
	ADDR_CODE_LV_LIANG_SHI AddrCode = "1730"
	// ADDR_CODE_FEN_YANG_SHI 汾阳市
	ADDR_CODE_FEN_YANG_SHI AddrCode = "1731"
	// ADDR_CODE_WEN_SHUI_XIAN 文水县
	ADDR_CODE_WEN_SHUI_XIAN AddrCode = "1732"
	// ADDR_CODE_JIAO_CHENG_XIAN 交城县
	ADDR_CODE_JIAO_CHENG_XIAN AddrCode = "1733"
	// ADDR_CODE_XIAO_YI_SHI 孝义市
	ADDR_CODE_XIAO_YI_SHI AddrCode = "1734"
	// ADDR_CODE_XING_XIAN 兴县
	ADDR_CODE_XING_XIAN AddrCode = "1735"
	// ADDR_CODE_LIN_XIAN 临县
	ADDR_CODE_LIN_XIAN AddrCode = "1736"
	// ADDR_CODE_LIU_LIN_XIAN 柳林县
	ADDR_CODE_LIU_LIN_XIAN AddrCode = "1737"
	// ADDR_CODE_SHI_LOU_XIAN 石楼县
	ADDR_CODE_SHI_LOU_XIAN AddrCode = "1738"
	// ADDR_CODE_LAN_XIAN 岚县
	ADDR_CODE_LAN_XIAN AddrCode = "1739"
	// ADDR_CODE_FANG_SHAN_XIAN 方山县
	ADDR_CODE_FANG_SHAN_XIAN AddrCode = "1741"
	// ADDR_CODE_ZHONG_YANG_XIAN 中阳县
	ADDR_CODE_ZHONG_YANG_XIAN AddrCode = "1743"
	// ADDR_CODE_JIAO_KOU_XIAN 交口县
	ADDR_CODE_JIAO_KOU_XIAN AddrCode = "1744"
	// ADDR_CODE_LI_SHI_QU 离石区
	ADDR_CODE_LI_SHI_QU AddrCode = "1745"
	// ADDR_CODE_JIN_ZHONG_SHI 晋中市
	ADDR_CODE_JIN_ZHONG_SHI AddrCode = "1750"
	// ADDR_CODE_YU_CI_QU 榆次区
	ADDR_CODE_YU_CI_QU AddrCode = "1751"
	// ADDR_CODE_YU_SHE_XIAN 榆社县
	ADDR_CODE_YU_SHE_XIAN AddrCode = "1752"
	// ADDR_CODE_ZUO_QUAN_XIAN 左权县
	ADDR_CODE_ZUO_QUAN_XIAN AddrCode = "1753"
	// ADDR_CODE_HE_SHUN_XIAN 和顺县
	ADDR_CODE_HE_SHUN_XIAN AddrCode = "1754"
	// ADDR_CODE_XI_YANG_XIAN 昔阳县
	ADDR_CODE_XI_YANG_XIAN AddrCode = "1755"
	// ADDR_CODE_SHOU_YANG_XIAN 寿阳县
	ADDR_CODE_SHOU_YANG_XIAN AddrCode = "1756"
	// ADDR_CODE_TAI_GU_QU 太谷区
	ADDR_CODE_TAI_GU_QU AddrCode = "1757"
	// ADDR_CODE_QI_XIAN 祁县
	ADDR_CODE_QI_XIAN AddrCode = "1758"
	// ADDR_CODE_PING_YAO_XIAN 平遥县
	ADDR_CODE_PING_YAO_XIAN AddrCode = "1759"
	// ADDR_CODE_JIE_XIU_SHI 介休市
	ADDR_CODE_JIE_XIU_SHI AddrCode = "1761"
	// ADDR_CODE_LING_SHI_XIAN 灵石县
	ADDR_CODE_LING_SHI_XIAN AddrCode = "1762"
	// ADDR_CODE_LIN_FEN_SHI 临汾市
	ADDR_CODE_LIN_FEN_SHI AddrCode = "1770"
	// ADDR_CODE_YAO_DU_QU 尧都区
	ADDR_CODE_YAO_DU_QU AddrCode = "1771"
	// ADDR_CODE_HOU_MA_SHI 侯马市
	ADDR_CODE_HOU_MA_SHI AddrCode = "1772"
	// ADDR_CODE_QU_WO_XIAN 曲沃县
	ADDR_CODE_QU_WO_XIAN AddrCode = "1773"
	// ADDR_CODE_YI_CHENG_XIAN 翼城县
	ADDR_CODE_YI_CHENG_XIAN AddrCode = "1774"
	// ADDR_CODE_XIANG_FEN_XIAN 襄汾县
	ADDR_CODE_XIANG_FEN_XIAN AddrCode = "1775"
	// ADDR_CODE_HONG_TONG_XIAN 洪洞县
	ADDR_CODE_HONG_TONG_XIAN AddrCode = "1776"
	// ADDR_CODE_HUO_ZHOU_SHI 霍州市
	ADDR_CODE_HUO_ZHOU_SHI AddrCode = "1777"
	// ADDR_CODE_GU_XIAN 古县
	ADDR_CODE_GU_XIAN AddrCode = "1778"
	// ADDR_CODE_AN_ZE_XIAN 安泽县
	ADDR_CODE_AN_ZE_XIAN AddrCode = "1779"
	// ADDR_CODE_FU_SHAN_XIAN 浮山县
	ADDR_CODE_FU_SHAN_XIAN AddrCode = "1781"
	// ADDR_CODE_JI_XIAN 吉县
	ADDR_CODE_JI_XIAN AddrCode = "1782"
	// ADDR_CODE_XIANG_NING_XIAN 乡宁县
	ADDR_CODE_XIANG_NING_XIAN AddrCode = "1783"
	// ADDR_CODE_PU_XIAN 蒲县
	ADDR_CODE_PU_XIAN AddrCode = "1784"
	// ADDR_CODE_DA_NING_XIAN 大宁县
	ADDR_CODE_DA_NING_XIAN AddrCode = "1785"
	// ADDR_CODE_YONG_HE_XIAN 永和县
	ADDR_CODE_YONG_HE_XIAN AddrCode = "1786"
	// ADDR_CODE_XI_XIAN 隰县
	ADDR_CODE_XI_XIAN AddrCode = "1787"
	// ADDR_CODE_FEN_XI_XIAN 汾西县
	ADDR_CODE_FEN_XI_XIAN AddrCode = "1788"
	// ADDR_CODE_YUN_CHENG_SHI 运城市
	ADDR_CODE_YUN_CHENG_SHI AddrCode = "1810"
	// ADDR_CODE_YAN_HU_QU 盐湖区
	ADDR_CODE_YAN_HU_QU AddrCode = "1811"
	// ADDR_CODE_YONG_JI_SHI 永济市
	ADDR_CODE_YONG_JI_SHI AddrCode = "1812"
	// ADDR_CODE_RUI_CHENG_XIAN 芮城县
	ADDR_CODE_RUI_CHENG_XIAN AddrCode = "1813"
	// ADDR_CODE_LIN_YI_XIAN 临猗县
	ADDR_CODE_LIN_YI_XIAN AddrCode = "1814"
	// ADDR_CODE_WAN_RONG_XIAN 万荣县
	ADDR_CODE_WAN_RONG_XIAN AddrCode = "1815"
	// ADDR_CODE_XIN_JIANG_XIAN 新绛县
	ADDR_CODE_XIN_JIANG_XIAN AddrCode = "1816"
	// ADDR_CODE_JI_SHAN_XIAN 稷山县
	ADDR_CODE_JI_SHAN_XIAN AddrCode = "1817"
	// ADDR_CODE_HE_JIN_SHI 河津市
	ADDR_CODE_HE_JIN_SHI AddrCode = "1818"
	// ADDR_CODE_WEN_XI_XIAN 闻喜县
	ADDR_CODE_WEN_XI_XIAN AddrCode = "1819"
	// ADDR_CODE_XIA_XIAN 夏县
	ADDR_CODE_XIA_XIAN AddrCode = "1821"
	// ADDR_CODE_JIANG_XIAN 绛县
	ADDR_CODE_JIANG_XIAN AddrCode = "1822"
	// ADDR_CODE_PING_LU_XIAN 平陆县
	ADDR_CODE_PING_LU_XIAN AddrCode = "1823"
	// ADDR_CODE_YUAN_QU_XIAN 垣曲县
	ADDR_CODE_YUAN_QU_XIAN AddrCode = "1824"
	// ADDR_CODE_NEI_MENG_GU_ZI_ZHI_QU 内蒙古自治区
	ADDR_CODE_NEI_MENG_GU_ZI_ZHI_QU AddrCode = "1900"
	// ADDR_CODE_HU_HE_HAO_TE_SHI 呼和浩特市
	ADDR_CODE_HU_HE_HAO_TE_SHI AddrCode = "1910"
	// ADDR_CODE_TU_MO_TE_ZUO_QI 土默特左旗
	ADDR_CODE_TU_MO_TE_ZUO_QI AddrCode = "1911"
	// ADDR_CODE_TUO_KE_TUO_XIAN 托克托县
	ADDR_CODE_TUO_KE_TUO_XIAN AddrCode = "1912"
	// ADDR_CODE_WU_CHUAN_XIAN 武川县
	ADDR_CODE_WU_CHUAN_XIAN AddrCode = "1913"
	// ADDR_CODE_HE_LIN_GE_ER_XIAN 和林格尔县
	ADDR_CODE_HE_LIN_GE_ER_XIAN AddrCode = "1914"
	// ADDR_CODE_QING_SHUI_HE_XIAN 清水河县
	ADDR_CODE_QING_SHUI_HE_XIAN AddrCode = "1915"
	// ADDR_CODE_HUI_MIN_QU 回民区
	ADDR_CODE_HUI_MIN_QU AddrCode = "1916"
	// ADDR_CODE_RU_YI_KAI_FA_QU 如意开发区
	ADDR_CODE_RU_YI_KAI_FA_QU AddrCode = "1917"
	// ADDR_CODE_SAI_HAN_QU 赛罕区
	ADDR_CODE_SAI_HAN_QU AddrCode = "1918"
	// ADDR_CODE_XIN_CHENG_QU 新城区
	ADDR_CODE_XIN_CHENG_QU AddrCode = "1919"
	// ADDR_CODE_BAO_TOU_SHI 包头市
	ADDR_CODE_BAO_TOU_SHI AddrCode = "1920"
	// ADDR_CODE_TU_MO_TE_YOU_QI 土默特右旗
	ADDR_CODE_TU_MO_TE_YOU_QI AddrCode = "1921"
	// ADDR_CODE_GU_YANG_XIAN 固阳县
	ADDR_CODE_GU_YANG_XIAN AddrCode = "1922"
	// ADDR_CODE_DA_ER_HAN_MAO_MING_AN_LIAN_HE_QI 达尔罕茂明安联合旗
	ADDR_CODE_DA_ER_HAN_MAO_MING_AN_LIAN_HE_QI AddrCode = "1923"
	// ADDR_CODE_DONG_HE_QU 东河区
	ADDR_CODE_DONG_HE_QU AddrCode = "1924"
	// ADDR_CODE_KUN_DOU_LUN_QU 昆都仑区
	ADDR_CODE_KUN_DOU_LUN_QU AddrCode = "1925"
	// ADDR_CODE_QING_SHAN_QU 青山区
	ADDR_CODE_QING_SHAN_QU AddrCode = "1926"
	// ADDR_CODE_SHI_GUAI_QU 石拐区
	ADDR_CODE_SHI_GUAI_QU AddrCode = "1927"
	// ADDR_CODE_BAI_YUN_E_BO_KUANG_QU 白云鄂博矿区
	ADDR_CODE_BAI_YUN_E_BO_KUANG_QU AddrCode = "1928"
	// ADDR_CODE_JIU_YUAN_QU 九原区
	ADDR_CODE_JIU_YUAN_QU AddrCode = "1929"
	// ADDR_CODE_WU_HAI_SHI 乌海市
	ADDR_CODE_WU_HAI_SHI AddrCode = "1930"
	// ADDR_CODE_HAI_BO_WAN_QU 海勃湾区
	ADDR_CODE_HAI_BO_WAN_QU AddrCode = "1931"
	// ADDR_CODE_HAI_NAN_QU 海南区
	ADDR_CODE_HAI_NAN_QU AddrCode = "1932"
	// ADDR_CODE_WU_DA_QU 乌达区
	ADDR_CODE_WU_DA_QU AddrCode = "1933"
	// ADDR_CODE_CHI_FENG_SHI 赤峰市
	ADDR_CODE_CHI_FENG_SHI AddrCode = "1940"
	// ADDR_CODE_A_LU_KE_ER_QIN_QI 阿鲁科尔沁旗
	ADDR_CODE_A_LU_KE_ER_QIN_QI AddrCode = "1941"
	// ADDR_CODE_BA_LIN_ZUO_QI 巴林左旗
	ADDR_CODE_BA_LIN_ZUO_QI AddrCode = "1942"
	// ADDR_CODE_BA_LIN_YOU_QI 巴林右旗
	ADDR_CODE_BA_LIN_YOU_QI AddrCode = "1943"
	// ADDR_CODE_LIN_XI_XIAN_TWO 林西县
	ADDR_CODE_LIN_XI_XIAN_TWO AddrCode = "1944"
	// ADDR_CODE_KE_SHI_KE_TENG_QI 克什克腾旗
	ADDR_CODE_KE_SHI_KE_TENG_QI AddrCode = "1945"
	// ADDR_CODE_WENG_NIU_TE_QI 翁牛特旗
	ADDR_CODE_WENG_NIU_TE_QI AddrCode = "1946"
	// ADDR_CODE_KA_LA_QIN_QI 喀喇沁旗
	ADDR_CODE_KA_LA_QIN_QI AddrCode = "1947"
	// ADDR_CODE_NING_CHENG_XIAN 宁城县
	ADDR_CODE_NING_CHENG_XIAN AddrCode = "1948"
	// ADDR_CODE_AO_HAN_QI 敖汉旗
	ADDR_CODE_AO_HAN_QI AddrCode = "1949"
	// ADDR_CODE_HONG_SHAN_QU 红山区
	ADDR_CODE_HONG_SHAN_QU AddrCode = "1951"
	// ADDR_CODE_YUAN_BAO_SHAN_QU 元宝山区
	ADDR_CODE_YUAN_BAO_SHAN_QU AddrCode = "1952"
	// ADDR_CODE_SONG_SHAN_QU 松山区
	ADDR_CODE_SONG_SHAN_QU AddrCode = "1953"
	// ADDR_CODE_HU_LUN_BEIER_SHI 呼伦贝尔市
	ADDR_CODE_HU_LUN_BEIER_SHI AddrCode = "1960"
	// ADDR_CODE_HAI_LA_ER_QU 海拉尔区
	ADDR_CODE_HAI_LA_ER_QU AddrCode = "1961"
	// ADDR_CODE_MAN_ZHOU_LI_SHI 满洲里市
	ADDR_CODE_MAN_ZHOU_LI_SHI AddrCode = "1962"
	// ADDR_CODE_ZHA_LAN_TUN_SHI 扎兰屯市
	ADDR_CODE_ZHA_LAN_TUN_SHI AddrCode = "1963"
	// ADDR_CODE_YA_KE_SHI_SHI 牙克石市
	ADDR_CODE_YA_KE_SHI_SHI AddrCode = "1964"
	// ADDR_CODE_ER_LUN_CHUN_ZU_ZI_ZHI_QI 额尔古纳市
	ADDR_CODE_ER_LUN_CHUN_ZU_ZI_ZHI_QI AddrCode = "1965"
)

// Pre 将AddrCode枚举转换为字符串
func (ac AddrCode) Pre() string {
	return string(ac)
}
