package consts

// AccIdType 证件类型枚举
type AccIdType string

const (
	// ACC_ID_TYPE_ID_CARD 身份证
	ACC_ID_TYPE_ID_CARD AccIdType = "01"
	// ACC_ID_TYPE_PASSPORT 护照
	ACC_ID_TYPE_PASSPORT AccIdType = "02"
	// ACC_ID_TYPE_HK_MO_PASS 港澳通行证
	ACC_ID_TYPE_HK_MO_PASS AccIdType = "03"
	// ACC_ID_TYPE_TAIWAN_PASS 台胞证
	ACC_ID_TYPE_TAIWAN_PASS AccIdType = "04"
	// ACC_ID_TYPE_FOREIGN_PERMANENT_RESIDENCE 外国人永久居留身份证
	ACC_ID_TYPE_FOREIGN_PERMANENT_RESIDENCE AccIdType = "10"
	// ACC_ID_TYPE_HK_MO_RESIDENCE 港澳居民居住证
	ACC_ID_TYPE_HK_MO_RESIDENCE AccIdType = "11"
	// ACC_ID_TYPE_TAIWAN_RESIDENCE 台湾居民居住证
	ACC_ID_TYPE_TAIWAN_RESIDENCE AccIdType = "12"
	// ACC_ID_TYPE_EXECUTIVE_PARTNER 执行事务合伙人
	ACC_ID_TYPE_EXECUTIVE_PARTNER AccIdType = "13"
	// ACC_ID_TYPE_OTHER 其它证件
	ACC_ID_TYPE_OTHER AccIdType = "99"
)

// Pre 将AccIdType枚举转换为字符串
func (ait AccIdType) Pre() string {
	return string(ait)
}

// SettlePeriod 结算周期枚举
type SettlePeriod string

const (
	// SETTLE_PERIOD_T_PLUS_1 T+1结算
	SETTLE_PERIOD_T_PLUS_1 SettlePeriod = "T+1"
	// SETTLE_PERIOD_T_PLUS_1_PLUS_N T+1普通结算批次
	SETTLE_PERIOD_T_PLUS_1_PLUS_N SettlePeriod = "T+1+N"
	// SETTLE_PERIOD_T_PLUS_3 收单T+3结算
	SETTLE_PERIOD_T_PLUS_3 SettlePeriod = "T+3"
	// SETTLE_PERIOD_D_PLUS_1_PLUS_N D+1普通结算批次
	SETTLE_PERIOD_D_PLUS_1_PLUS_N SettlePeriod = "D+1+N"
	// SETTLE_PERIOD_W_T_PLUS_9999 喔噻T+9999
	SETTLE_PERIOD_W_T_PLUS_9999 SettlePeriod = "W_T+9999"
	// SETTLE_PERIOD_D_PLUS_1 收单D+1结算批次
	SETTLE_PERIOD_D_PLUS_1 SettlePeriod = "D+1"
	// SETTLE_PERIOD_D1_PLUS_24 D1+24结算批次
	SETTLE_PERIOD_D1_PLUS_24 SettlePeriod = "D1+24"
	// SETTLE_PERIOD_D_PLUS_30 收单D+30结算
	SETTLE_PERIOD_D_PLUS_30 SettlePeriod = "D+30"
	// SETTLE_PERIOD_BT_D_PLUS_1 D+1四方补贴结算批次
	SETTLE_PERIOD_BT_D_PLUS_1 SettlePeriod = "BT_D+1"
	// SETTLE_PERIOD_QZT_FULL_D_PLUS_1 钱账通D+1全额结算批次
	SETTLE_PERIOD_QZT_FULL_D_PLUS_1 SettlePeriod = "QZT_FULL_D+1"
	// SETTLE_PERIOD_QZT_NET_D_PLUS_1 钱账通D+1净额结算批次
	SETTLE_PERIOD_QZT_NET_D_PLUS_1 SettlePeriod = "QZT_NET_D+1"
	// SETTLE_PERIOD_FS 灵活结算
	SETTLE_PERIOD_FS SettlePeriod = "FS"
)

// Pre 将SettlePeriod枚举转换为字符串
func (sp SettlePeriod) Pre() string {
	return string(sp)
}

// ClearDt 日切时间枚举
type ClearDt string

const (
	// CLEAR_DT_ZERO 0点
	CLEAR_DT_ZERO ClearDt = "ZERO"
	// CLEAR_DT_ONE 1点
	CLEAR_DT_ONE ClearDt = "ONE"
	// CLEAR_DT_TWO 2点
	CLEAR_DT_TWO ClearDt = "TWO"
	// CLEAR_DT_THREE 3点
	CLEAR_DT_THREE ClearDt = "THREE"
	// CLEAR_DT_FOUR 4点
	CLEAR_DT_FOUR ClearDt = "FOUR"
	// CLEAR_DT_FIVE 5点
	CLEAR_DT_FIVE ClearDt = "FIVE"
	// CLEAR_DT_SIX 6点
	CLEAR_DT_SIX ClearDt = "SIX"
	// CLEAR_DT_SEVEN 7点
	CLEAR_DT_SEVEN ClearDt = "SEVEN"
	// CLEAR_DT_EIGHT 8点
	CLEAR_DT_EIGHT ClearDt = "EIGHT"
	// CLEAR_DT_NINE 9点
	CLEAR_DT_NINE ClearDt = "NINE"
	// CLEAR_DT_TEN 10点
	CLEAR_DT_TEN ClearDt = "TEN"
	// CLEAR_DT_ELEVEN 11点
	CLEAR_DT_ELEVEN ClearDt = "ELEVEN"
	// CLEAR_DT_TWELVE 12点
	CLEAR_DT_TWELVE ClearDt = "TWELVE"
	// CLEAR_DT_THIRTEEN 13点
	CLEAR_DT_THIRTEEN ClearDt = "THIRTEEN"
	// CLEAR_DT_FOURTEEN 14点
	CLEAR_DT_FOURTEEN ClearDt = "FOURTEEN"
	// CLEAR_DT_FIFTEEN 15点
	CLEAR_DT_FIFTEEN ClearDt = "FIFTEEN"
	// CLEAR_DT_SIXTEEN 16点
	CLEAR_DT_SIXTEEN ClearDt = "SIXTEEN"
	// CLEAR_DT_SEVENTEEN 17点
	CLEAR_DT_SEVENTEEN ClearDt = "SEVENTEEN"
	// CLEAR_DT_EIGHTEEN 18点
	CLEAR_DT_EIGHTEEN ClearDt = "EIGHTEEN"
	// CLEAR_DT_NINETEEN 19点
	CLEAR_DT_NINETEEN ClearDt = "NINETEEN"
	// CLEAR_DT_TWENTY 20点
	CLEAR_DT_TWENTY ClearDt = "TWENTY"
	// CLEAR_DT_TWENTY_ONE 21点
	CLEAR_DT_TWENTY_ONE ClearDt = "TWENTY_ONE"
	// CLEAR_DT_TWENTY_TWO 22点
	CLEAR_DT_TWENTY_TWO ClearDt = "TWENTY_TWO"
	// CLEAR_DT_TWENTY_THREE 23点
	CLEAR_DT_TWENTY_THREE ClearDt = "TWENTY_THREE"
	// CLEAR_DT_TWENTY_FOUR 24点
	CLEAR_DT_TWENTY_FOUR ClearDt = "TWENTY_FOUR"
)

// Pre 将ClearDt枚举转换为字符串
func (cd ClearDt) Pre() string {
	return string(cd)
}

// MerBusiContent 经营内容枚举
type MerBusiContent string

const (
	// MER_BUSI_CONTENT_RESTAURANT_HOTEL 餐饮、宾馆、娱乐、珠宝金饰、工艺美术品
	MER_BUSI_CONTENT_RESTAURANT_HOTEL MerBusiContent = "640"
	// MER_BUSI_CONTENT_REAL_ESTATE_AUTO 房地产汽车类
	MER_BUSI_CONTENT_REAL_ESTATE_AUTO MerBusiContent = "641"
	// MER_BUSI_CONTENT_DEPARTMENT_AGENCY 百货、中介、培训、景区门票等
	MER_BUSI_CONTENT_DEPARTMENT_AGENCY MerBusiContent = "642"
	// MER_BUSI_CONTENT_WHOLESALE 批发类商户
	MER_BUSI_CONTENT_WHOLESALE MerBusiContent = "643"
	// MER_BUSI_CONTENT_GAS_STATION_SUPERMARKET 加油、超市类
	MER_BUSI_CONTENT_GAS_STATION_SUPERMARKET MerBusiContent = "644"
	// MER_BUSI_CONTENT_TRANSPORT_TICKET 交通运输售票
	MER_BUSI_CONTENT_TRANSPORT_TICKET MerBusiContent = "645"
	// MER_BUSI_CONTENT_UTILITY_PAYMENT 水电气缴费
	MER_BUSI_CONTENT_UTILITY_PAYMENT MerBusiContent = "646"
	// MER_BUSI_CONTENT_GOVERNMENT 政府类
	MER_BUSI_CONTENT_GOVERNMENT MerBusiContent = "647"
	// MER_BUSI_CONTENT_CONVENIENCE 便民类
	MER_BUSI_CONTENT_CONVENIENCE MerBusiContent = "648"
	// MER_BUSI_CONTENT_PUBLIC_INSTITUTION 公立医院、公立学校、慈善
	MER_BUSI_CONTENT_PUBLIC_INSTITUTION MerBusiContent = "649"
	// MER_BUSI_CONTENT_HOTEL_FOOD_ENTERTAINMENT 宾馆餐饮娱乐类
	MER_BUSI_CONTENT_HOTEL_FOOD_ENTERTAINMENT MerBusiContent = "650"
	// MER_BUSI_CONTENT_PROPERTY_AUTO 房产汽车类
	MER_BUSI_CONTENT_PROPERTY_AUTO MerBusiContent = "651"
	// MER_BUSI_CONTENT_WHOLESALE_TYPE 批发类
	MER_BUSI_CONTENT_WHOLESALE_TYPE MerBusiContent = "652"
	// MER_BUSI_CONTENT_SUPERMARKET_GAS 超市加油类
	MER_BUSI_CONTENT_SUPERMARKET_GAS MerBusiContent = "653"
	// MER_BUSI_CONTENT_GENERAL_MERCHANT 一般类商户
	MER_BUSI_CONTENT_GENERAL_MERCHANT MerBusiContent = "654"
	// MER_BUSI_CONTENT_AGRICULTURE 三农商户
	MER_BUSI_CONTENT_AGRICULTURE MerBusiContent = "655"
)

// Pre 将MerBusiContent枚举转换为字符串
func (mbc MerBusiContent) Pre() string {
	return string(mbc)
}

// PosType POS类型枚举
type PosType string

const (
	// POS_TYPE_GENERAL_POS 传统POS
	POS_TYPE_GENERAL_POS PosType = "GENERAL_POS"
	// POS_TYPE_SUPER_POS 智能POS
	POS_TYPE_SUPER_POS PosType = "SUPER_POS"
	// POS_TYPE_BLUE_WIZARD 蓝精灵
	POS_TYPE_BLUE_WIZARD PosType = "BLUE_WIZARD"
	// POS_TYPE_WECHAT_PAY 专业化扫码
	POS_TYPE_WECHAT_PAY PosType = "WECHAT_PAY"
	// POS_TYPE_SQB_SCAN_CODE 收钱吧扫码
	POS_TYPE_SQB_SCAN_CODE PosType = "SQB_SCAN_CODE"
	// POS_TYPE_SQB_PAPER_CODE 收钱吧码牌
	POS_TYPE_SQB_PAPER_CODE PosType = "SQB_PAPER_CODE"
	// POS_TYPE_SQB_DESK_CODE 收钱吧桌码
	POS_TYPE_SQB_DESK_CODE PosType = "SQB_DESK_CODE"
	// POS_TYPE_SQB_POS 收钱吧POS
	POS_TYPE_SQB_POS PosType = "SQB_POS"
	// POS_TYPE_SQB_INSTALLMENT 收钱吧聚分期
	POS_TYPE_SQB_INSTALLMENT PosType = "SQB_INSTALLMENT"
	// POS_TYPE_CLOUD_STORE_NEW 新云小店
	POS_TYPE_CLOUD_STORE_NEW PosType = "CLOUD_STORE_NEW"
	// POS_TYPE_CLOUD_DISTRIBUTION 增商专用云分销
	POS_TYPE_CLOUD_DISTRIBUTION PosType = "CLOUD_DISTRIBUTION"
	// POS_TYPE_CLOUD_DISTRIBUTION_CB 云分销线上
	POS_TYPE_CLOUD_DISTRIBUTION_CB PosType = "CLOUD_DISTRIBUTION_CB"
	// POS_TYPE_CLOUD_STORE_CB 云小店线上
	POS_TYPE_CLOUD_STORE_CB PosType = "CLOUD_STORE_CB"
	// POS_TYPE_CLOUD_STORE_BC 云小店线下
	POS_TYPE_CLOUD_STORE_BC PosType = "CLOUD_STORE_BC"
	// POS_TYPE_CLOUD_STORE_BC_NOTLKL 云小店非收银机
	POS_TYPE_CLOUD_STORE_BC_NOTLKL PosType = "CLOUD_STORE_BC_NOTLKL"
	// POS_TYPE_HM 惠码
	POS_TYPE_HM PosType = "HM"
	// POS_TYPE_HM_CB 惠码线上
	POS_TYPE_HM_CB PosType = "HM_CB"
	// POS_TYPE_HM_BC 惠码线下
	POS_TYPE_HM_BC PosType = "HM_BC"
	// POS_TYPE_SCAN_CODE_ORDER 扫码点餐
	POS_TYPE_SCAN_CODE_ORDER PosType = "SCAN_CODE_ORDER"
	// POS_TYPE_B2B_CASHIER_DESK B2B收银台
	POS_TYPE_B2B_CASHIER_DESK PosType = "B2B_CASHIER_DESK"
	// POS_TYPE_B2B_QR_CODE B2B收款码
	POS_TYPE_B2B_QR_CODE PosType = "B2B_QR_CODE"
	// POS_TYPE_MOBILE_POS 手机POS
	POS_TYPE_MOBILE_POS PosType = "MOBILE_POS"
	// POS_TYPE_YF_YM 御风云码
	POS_TYPE_YF_YM PosType = "YF_YM"
	// POS_TYPE_YF_YM_CB 御风云码线上
	POS_TYPE_YF_YM_CB PosType = "YF_YM_CB"
	// POS_TYPE_TRANSFER_ACCOUNT 大额理财
	POS_TYPE_TRANSFER_ACCOUNT PosType = "TRANSFER_ACCOUNT"
	// POS_TYPE_SUPER_MPOS 超级收款宝
	POS_TYPE_SUPER_MPOS PosType = "SUPER_MPOS"
	// POS_TYPE_W_BOX 收钱宝盒
	POS_TYPE_W_BOX PosType = "W_BOX"
	// POS_TYPE_MOON_BOS 月光宝盒
	POS_TYPE_MOON_BOS PosType = "MOON_BOS"
	// POS_TYPE_SCANNING_GUN_PAY XQ码精灵
	POS_TYPE_SCANNING_GUN_PAY PosType = "SCANNING_GUN_PAY"
	// POS_TYPE_WIDE_SUPER_POS 智能POS PRO
	POS_TYPE_WIDE_SUPER_POS PosType = "WIDE_SUPER_POS"
	// POS_TYPE_YUNCHAO_TECH_CB 云超科技线上
	POS_TYPE_YUNCHAO_TECH_CB PosType = "YUNCHAO_TECH_CB"
	// POS_TYPE_YUNCHAO_TECH_BC 云超科技线下
	POS_TYPE_YUNCHAO_TECH_BC PosType = "YUNCHAO_TECH_BC"
	// POS_TYPE_HUMMING_BIRD 蜂鸟佳
	POS_TYPE_HUMMING_BIRD PosType = "HUMMING_BIRD"
	// POS_TYPE_SIMPLE_SPEED_SCRM 简速SCRM
	POS_TYPE_SIMPLE_SPEED_SCRM PosType = "SIMPLE_SPEED_SCRM"
	// POS_TYPE_SMART_NETWORK 智网
	POS_TYPE_SMART_NETWORK PosType = "SMART_NETWORK"
	// POS_TYPE_EASY_PAYMENT 缴费易
	POS_TYPE_EASY_PAYMENT PosType = "EASY_PAYMENT"
	// POS_TYPE_LIANTUO_ELF 联拓小精灵
	POS_TYPE_LIANTUO_ELF PosType = "LIANTUO_ELF"
	// POS_TYPE_KAOLA_CLOUD_PAY 考拉云付
	POS_TYPE_KAOLA_CLOUD_PAY PosType = "KAOLA_CLOUD_PAY"
	// POS_TYPE_BUSINESS_CLOUD_PRINT 拉生意云打印
	POS_TYPE_BUSINESS_CLOUD_PRINT PosType = "BUSINESS_CLOUD_PRINT"
	// POS_TYPE_B2B_CASHIER_DESK_CB B2B收银台线上外卡
	POS_TYPE_B2B_CASHIER_DESK_CB PosType = "B2B_CASHIER_DESK_CB"
	// POS_TYPE_MOBILE_POS_CB 手机POS线上外卡
	POS_TYPE_MOBILE_POS_CB PosType = "MOBILE_POS_CB"
	// POS_TYPE_LKL_SCRM 拉卡拉SCRM
	POS_TYPE_LKL_SCRM PosType = "LKL_SCRM"
	// POS_TYPE_MI_XUN 米讯
	POS_TYPE_MI_XUN PosType = "MI_XUN"
	// POS_TYPE_YOU_KE_LI_LI 油客里里
	POS_TYPE_YOU_KE_LI_LI PosType = "YOU_KE_LI_LI"
	// POS_TYPE_LE_YOU_KE 乐友客
	POS_TYPE_LE_YOU_KE PosType = "LE_YOU_KE"
	// POS_TYPE_EASY_TO_PAY 即易付
	POS_TYPE_EASY_TO_PAY PosType = "EASY_TO_PAY"
	// POS_TYPE_SMART_YOUKE 智慧油客
	POS_TYPE_SMART_YOUKE PosType = "SMART_YOUKE"
	// POS_TYPE_MICRO_SUPER_POS 微智能
	POS_TYPE_MICRO_SUPER_POS PosType = "MICRO_SUPER_POS"
	// POS_TYPE_JI_YI_SHOU 集易收
	POS_TYPE_JI_YI_SHOU PosType = "JI_YI_SHOU"
	// POS_TYPE_UNIONPAY_APPLET 云微小程序
	POS_TYPE_UNIONPAY_APPLET PosType = "UNIONPAY_APPLET"
	// POS_TYPE_UNION_INSTALMENT 银联聚分期
	POS_TYPE_UNION_INSTALMENT PosType = "UNION_INSTALMENT"
	// POS_TYPE_PULL_BUSINESS 拉生意
	POS_TYPE_PULL_BUSINESS PosType = "PULL_BUSINESS"
	// POS_TYPE_MOSS Moss收银台
	POS_TYPE_MOSS PosType = "MOSS"
)

// Pre 将PosType枚举转换为字符串
func (pt PosType) Pre() string {
	return string(pt)
}

// FeeRateTypeCode 费率类型枚举
type FeeRateTypeCode string

const (
	// FEE_RATE_TYPE_CODE_UNIONPAY_DEBIT 银联借记卡
	FEE_RATE_TYPE_CODE_UNIONPAY_DEBIT FeeRateTypeCode = "300"
	// FEE_RATE_TYPE_CODE_UNIONPAY_CREDIT 银联贷记卡
	FEE_RATE_TYPE_CODE_UNIONPAY_CREDIT FeeRateTypeCode = "301"
	// FEE_RATE_TYPE_CODE_WECHAT 微信
	FEE_RATE_TYPE_CODE_WECHAT FeeRateTypeCode = "302"
	// FEE_RATE_TYPE_CODE_WECHAT_DEBIT 微信借记
	FEE_RATE_TYPE_CODE_WECHAT_DEBIT FeeRateTypeCode = "338"
	// FEE_RATE_TYPE_CODE_WECHAT_CREDIT 微信贷记
	FEE_RATE_TYPE_CODE_WECHAT_CREDIT FeeRateTypeCode = "339"
	// FEE_RATE_TYPE_CODE_ALIPAY 支付宝
	FEE_RATE_TYPE_CODE_ALIPAY FeeRateTypeCode = "303"
	// FEE_RATE_TYPE_CODE_YEEPAY 翼支付
	FEE_RATE_TYPE_CODE_YEEPAY FeeRateTypeCode = "306"
	// FEE_RATE_TYPE_CODE_UNIONPAY_QR_DEBIT 银联二维码借记卡
	FEE_RATE_TYPE_CODE_UNIONPAY_QR_DEBIT FeeRateTypeCode = "314"
	// FEE_RATE_TYPE_CODE_UNIONPAY_QR_CREDIT 银联二维码贷记卡
	FEE_RATE_TYPE_CODE_UNIONPAY_QR_CREDIT FeeRateTypeCode = "315"
	// FEE_RATE_TYPE_CODE_CARDLESS_CREDIT 无卡贷记
	FEE_RATE_TYPE_CODE_CARDLESS_CREDIT FeeRateTypeCode = "321"
	// FEE_RATE_TYPE_CODE_PAY_ACCOUNT 支付账户
	FEE_RATE_TYPE_CODE_PAY_ACCOUNT FeeRateTypeCode = "319"
	// FEE_RATE_TYPE_CODE_B2B_TRANSFER B2B转账
	FEE_RATE_TYPE_CODE_B2B_TRANSFER FeeRateTypeCode = "322"
	// FEE_RATE_TYPE_CODE_WECHAT_ONLINE 微信线上（千米专用）
	FEE_RATE_TYPE_CODE_WECHAT_ONLINE FeeRateTypeCode = "400"
	// FEE_RATE_TYPE_CODE_ALIPAY_ONLINE 支付宝线上（千米专用）
	FEE_RATE_TYPE_CODE_ALIPAY_ONLINE FeeRateTypeCode = "401"
	// FEE_RATE_TYPE_CODE_WECHAT_FACE 微信刷脸
	FEE_RATE_TYPE_CODE_WECHAT_FACE FeeRateTypeCode = "307"
	// FEE_RATE_TYPE_CODE_WECHAT_FACE_DEBIT 微信刷脸借记
	FEE_RATE_TYPE_CODE_WECHAT_FACE_DEBIT FeeRateTypeCode = "342"
	// FEE_RATE_TYPE_CODE_WECHAT_FACE_CREDIT 微信刷脸贷记
	FEE_RATE_TYPE_CODE_WECHAT_FACE_CREDIT FeeRateTypeCode = "343"
	// FEE_RATE_TYPE_CODE_ALIPAY_FACE 支付宝刷脸
	FEE_RATE_TYPE_CODE_ALIPAY_FACE FeeRateTypeCode = "308"
	// FEE_RATE_TYPE_CODE_UNIONPAY_DISCOUNT_DEBIT 云闪付借记-优惠
	FEE_RATE_TYPE_CODE_UNIONPAY_DISCOUNT_DEBIT FeeRateTypeCode = "411"
	// FEE_RATE_TYPE_CODE_UNIONPAY_DISCOUNT_CREDIT 云闪付贷记-优惠
	FEE_RATE_TYPE_CODE_UNIONPAY_DISCOUNT_CREDIT FeeRateTypeCode = "412"
	// FEE_RATE_TYPE_CODE_UNIONPAY_QR_DISCOUNT_DEBIT 银联二维码借记-优惠
	FEE_RATE_TYPE_CODE_UNIONPAY_QR_DISCOUNT_DEBIT FeeRateTypeCode = "413"
	// FEE_RATE_TYPE_CODE_UNIONPAY_QR_DISCOUNT_CREDIT 银联二维码贷记-优惠
	FEE_RATE_TYPE_CODE_UNIONPAY_QR_DISCOUNT_CREDIT FeeRateTypeCode = "414"
	// FEE_RATE_TYPE_CODE_ALIPAY_DISCOUNT 支付宝费率-优惠
	FEE_RATE_TYPE_CODE_ALIPAY_DISCOUNT FeeRateTypeCode = "415"
	// FEE_RATE_TYPE_CODE_DIGITAL_CURRENCY 数字货币
	FEE_RATE_TYPE_CODE_DIGITAL_CURRENCY FeeRateTypeCode = "318"
	// FEE_RATE_TYPE_CODE_JINGDONG 京东
	FEE_RATE_TYPE_CODE_JINGDONG FeeRateTypeCode = "346"
)

// Pre 将FeeRateTypeCode枚举转换为字符串
func (frtc FeeRateTypeCode) Pre() string {
	return string(frtc)
}
